# lx03 のサンプルコード

- 例外って何？ -- 困った状況 1-7

    `exceptions.scala`: `runMain ExceptionsLab`

- 自分から例外を発生してみよう

    `throws.scala`: `runMain FactNormal`, `runMain FactNegative`, `runMain FactTooLarge`

- 例外を掴まえてみよう

    `trycatch.scala`: `runMain TryCatch`, `runMain TryFactorial`
